### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by grumdrig** [Squishy47/Schroeder-All-Pass-Filter#1]
The code all makes sense to me except this line:

    delay = delay * (1 - (g * g));

Looking at the definition of the Schroeder all-pass I don't understand where that scaling by `1-g^2` would come from. I might just not understand how this stuff works. I'd very much appreciate it if you're able to explain.

**Comment by Squishy47** [comment]
yep looking at the spec for a schroeder all-pass this is wrong. i'll push a change. probs why my reverb sounded like trash... :p
have pushed change now.
